server:
  port: 8101

spring:

  datasource:
    url:  "jdbc:postgresql://localhost:5432/mediatheque"
    username: postgres
    password: admin
#    username: daf_qlf
#    password: P=B2q"FG6s
# Redis
#  redis:
#    host: localhost
#    port: 6379

# webservices-mediatheque-api
webservices-mediatheque-api:
  dashboard:
    url: http://localhost:8101




