server:
  port: 8100

spring:
  security:
    authentication:
      jwt:
        #publickey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEApRoGPrQDzAF2i2P8wuSHlScgSRiHA7fgYtpH/14wejlLqqCLVbPjUm11n1uMuhKUhzjdspvDYA1405o9uAs51F+mt5tgakQNww4rc0rlEkdPyTV6VqnROp7ZGVcl77Ab21CVlv30+SGCY442TjKzcwIR5areGWBevmdl9iPTwl7IBxGtGY4fxyX0xzqPLqUTEN3musvNzqjx+yR+FUn3YerOV81NXXO0WoDIvgMdeeQ9vAqlU0yKy3qp3R++gOUu/qihEYFSZPRiswQBuix50532RP+95P/VGaoL4rkiXN3mWp0qa6/cW+yFdLrjnb+oanHlHYVk9FI/hWabx9ZA2QIDAQAB